"""Reviewer-grade statistics on existing data: terminal-round per-cell accuracy with
Wilson 95% CIs, ee-D decomposition check, key pairwise two-proportion tests +
bootstrap CIs on p_truth, and a calibration check (round-0 belief vs Bayesian
single-signal posterior). Stdlib only. Writes stats_report.md."""
from __future__ import annotations
import csv, math, random
from collections import defaultdict
from pathlib import Path

random.seed(12345)
HERE = Path(__file__).parent
DIRS = ["gpt-4.1-mini", "claude-sonnet-4-6", "gpt-4.1-mini_n11",
        "gpt-4.1-mini_degree", "gpt-4.1-mini_sigsweep",
        "gemini-2.5-flash", "gemini-2.5-pro"]


def terminal_rows(tag):
    """Return list of terminal-round rows (one per trial), keyed cells."""
    p = HERE / "data" / tag / "rounds.csv"
    if not p.exists():
        return None
    best = {}  # (regime,topo,content,seed) -> (round, row)
    with open(p) as f:
        for r in csv.DictReader(f):
            k = (r["regime"], r["topology"], r["content_mode"], r["seed"])
            rd = int(r["round"])
            if k not in best or rd > best[k][0]:
                best[k] = (rd, r)
    return [v[1] for v in best.values()]


def wilson(k, n, z=1.96):
    if n == 0:
        return (0.0, 0.0, 0.0)
    p = k / n
    d = 1 + z*z/n
    c = (p + z*z/(2*n)) / d
    h = z*math.sqrt(p*(1-p)/n + z*z/(4*n*n)) / d
    return (p, max(0.0, c-h), min(1.0, c+h))


def two_prop_z(k1, n1, k2, n2):
    if n1 == 0 or n2 == 0:
        return float("nan"), float("nan")
    p1, p2 = k1/n1, k2/n2
    pp = (k1+k2)/(n1+n2)
    se = math.sqrt(pp*(1-pp)*(1/n1+1/n2))
    if se == 0:
        return float("inf") if p1 != p2 else 0.0, 0.0 if p1 != p2 else 1.0
    z = (p1-p2)/se
    pval = 2*(1-0.5*(1+math.erf(abs(z)/math.sqrt(2))))
    return z, pval


def boot_diff(a, b, B=10000):
    if not a or not b:
        return (float("nan"),)*3
    da = a[:]; db = b[:]
    diffs = []
    na, nb = len(da), len(db)
    for _ in range(B):
        ma = sum(da[random.randrange(na)] for _ in range(na))/na
        mb = sum(db[random.randrange(nb)] for _ in range(nb))/nb
        diffs.append(ma-mb)
    diffs.sort()
    return (sum(a)/len(a)-sum(b)/len(b), diffs[int(0.025*B)], diffs[int(0.975*B)])


def cell_stats(rows):
    cells = defaultdict(lambda: {"acc_lo": [], "acc_m": [], "ebar": [], "D": [],
                                 "regret": [], "ptruth": [], "collm": [], "y": []})
    for r in rows:
        k = (r["regime"], r["topology"], r["content_mode"])
        c = cells[k]
        c["acc_lo"].append(int(r["acc_logodds"]))
        c["acc_m"].append(int(r["acc_mean"]))
        c["ebar"].append(float(r["e_bar"]))
        c["D"].append(float(r["D"]))
        c["regret"].append(float(r["regret_logodds"]))
        c["ptruth"].append(float(r["p_truth_logodds"]))
        c["collm"].append(float(r["coll_mean"]))
        c["y"].append(1.0 if r["true_state"] == "A" else 0.0)
    return cells


def fmt_pct(p, lo, hi):
    return f"{p:.2f} [{lo:.2f},{hi:.2f}]"


out = ["# Statistics report (existing data) — generated by analyze_stats.py\n"]
ALLCELLS = {}
for tag in DIRS:
    rows = terminal_rows(tag)
    if rows is None:
        out.append(f"\n## {tag}: NO DATA\n"); continue
    cells = cell_stats(rows)
    ALLCELLS[tag] = cells
    out.append(f"\n## {tag}\n")
    out.append("| regime | topology | content | N | acc_logodds [95% Wilson] | acc_mean | ē | D | regret | P(truth) |")
    out.append("|---|---|---|---|---|---|---|---|---|---|")
    for k in sorted(cells):
        c = cells[k]; n = len(c["acc_lo"])
        klo = sum(c["acc_lo"]); p, lo, hi = wilson(klo, n)
        am = sum(c["acc_m"])/n
        eb = sum(c["ebar"])/n; D = sum(c["D"])/n
        rg = sum(c["regret"])/n; pt = sum(c["ptruth"])/n
        out.append(f"| {k[0]} | {k[1]} | {k[2]} | {n} | {fmt_pct(p,lo,hi)} | {am:.2f} | "
                   f"{eb:.3f} | {D:.3f} | {rg:.3f} | {pt:.3f} |")

# ---- ee-D decomposition check (mean pool): collective Brier ?= ebar - D ----
out.append("\n## ē−D decomposition check (mean pool): collective Brier vs (ē − D)\n")
out.append("For each terminal trial, (coll_mean − y)^2 should equal e_bar − D (Page identity, quadratic loss).")
maxerr = 0.0
for tag in DIRS:
    if tag not in ALLCELLS: continue
    rows = terminal_rows(tag)
    errs = []
    for r in rows:
        y = 1.0 if r["true_state"] == "A" else 0.0
        cb = (float(r["coll_mean"]) - y)**2
        rhs = float(r["e_bar"]) - float(r["D"])
        errs.append(abs(cb-rhs))
    me = max(errs) if errs else 0.0
    maxerr = max(maxerr, me)
    out.append(f"- {tag}: max |collBrier − (ē−D)| = {me:.4g} over {len(errs)} trials "
               f"({'identity holds' if me < 1e-6 else 'CHECK'})")
out.append(f"\n=> decomposition exact to {maxerr:.2g}; report ē/D on the MEAN pool; "
           f"note acc is scored on the log-odds pool separately.")

# ---- Key pairwise contrasts ----
def get(tag, regime, topo, content, field):
    c = ALLCELLS.get(tag, {}).get((regime, topo, content))
    return c[field] if c else []

out.append("\n## Key pairwise contrasts\n")
contrasts = [
    ("gpt-4.1-mini", "misleading_majority", "all_channel", "evidence_only", "conclusion_only", "evidence vs conclusion (n5)"),
    ("gpt-4.1-mini", "misleading_majority", "baseline", "none", None, None),  # placeholder skip
    ("claude-sonnet-4-6", "misleading_majority", "all_channel", "evidence_only", "conclusion_only", "evidence vs conclusion (Sonnet)"),
    ("gpt-4.1-mini_n11", "misleading_majority", "all_channel", "conclusion_only", None, None),
]
def contrast(tag, regime, topoA, cA, topoB, cB, label):
    a_acc = get(tag, regime, topoA, cA, "acc_lo")
    b_acc = get(tag, regime, topoB, cB, "acc_lo")
    if not a_acc or not b_acc:
        return f"- [{tag}] {label}: MISSING ({topoA}/{cA} N={len(a_acc)}, {topoB}/{cB} N={len(b_acc)})"
    z, pv = two_prop_z(sum(a_acc), len(a_acc), sum(b_acc), len(b_acc))
    a_pt = get(tag, regime, topoA, cA, "ptruth"); b_pt = get(tag, regime, topoB, cB, "ptruth")
    d, dlo, dhi = boot_diff(a_pt, b_pt)
    return (f"- [{tag}] {label}: acc {sum(a_acc)/len(a_acc):.2f} (N={len(a_acc)}) vs "
            f"{sum(b_acc)/len(b_acc):.2f} (N={len(b_acc)}); two-prop z={z:.2f}, p={pv:.2g}; "
            f"ΔP(truth)={d:+.2f} [{dlo:+.2f},{dhi:+.2f}]")

# evidence vs conclusion, all_channel, misleading, each model + n11
for tag in ["gpt-4.1-mini", "claude-sonnet-4-6", "gpt-4.1-mini_n11"]:
    out.append(contrast(tag, "misleading_majority", "all_channel", "evidence_only",
                        "all_channel", "conclusion_only", "evidence vs conclusion (all_channel)"))
# baseline vs conclusion
for tag in ["gpt-4.1-mini", "claude-sonnet-4-6"]:
    out.append(contrast(tag, "misleading_majority", "baseline", "none",
                        "all_channel", "conclusion_only", "baseline vs conclusion"))
# topology: all_channel vs circle (conclusion), n11; and small-world vs all_channel
out.append(contrast("gpt-4.1-mini_n11", "misleading_majority", "circle", "conclusion_only",
                    "all_channel", "conclusion_only", "circle vs all_channel (conclusion)"))
out.append(contrast("gpt-4.1-mini_n11", "misleading_majority", "ring_shortcuts", "conclusion_only",
                    "all_channel", "conclusion_only", "small-world vs all_channel (conclusion)"))
out.append(contrast("gpt-4.1-mini_n11", "misleading_majority", "ring_shortcuts", "conclusion_only",
                    "circle", "conclusion_only", "small-world vs circle (conclusion)"))

# ---- Calibration: round-0 individual belief vs single-signal Bayesian posterior ----
out.append("\n## Calibration: round-0 belief vs single-signal Bayesian posterior (beliefs.csv)\n")
for tag in DIRS:
    p = HERE / "data" / tag / "beliefs.csv"
    if not p.exists():
        out.append(f"- {tag}: no beliefs.csv"); continue
    bel, post = [], []
    with open(p) as f:
        for r in csv.DictReader(f):
            if int(r["round"]) != 0:
                continue
            try:
                bel.append(float(r["belief_pA"])); post.append(float(r["private_post_a"]))
            except (ValueError, KeyError):
                pass
    if not bel:
        out.append(f"- {tag}: no round-0 rows"); continue
    n = len(bel)
    mae = sum(abs(b-q) for b, q in zip(bel, post))/n
    mse = sum(abs(b-q) for b, q in zip(bel, post))  # signed
    signed = sum(b-q for b, q in zip(bel, post))/n
    mb, mp = sum(bel)/n, sum(post)/n
    cov = sum((b-mb)*(q-mp) for b, q in zip(bel, post))/n
    sb = math.sqrt(sum((b-mb)**2 for b in bel)/n); sp = math.sqrt(sum((q-mp)**2 for q in post)/n)
    rho = cov/(sb*sp) if sb*sp > 0 else float("nan")
    out.append(f"- {tag}: N={n} round-0 beliefs; Pearson r(belief, Bayes posterior)={rho:.3f}; "
               f"MAE={mae:.3f}; mean signed (belief−Bayes)={signed:+.3f}")

report = "\n".join(out) + "\n"
(HERE / "stats_report.md").write_text(report)
print(report)
